const skillList = [
  { title: 'Kotlin', year: 3 },
  { title: 'TensorFlow', year: 1 },
  { title: 'D3.js', year: 5 },
  { title: 'Adobe XD', year: 2 },
  { title: 'MATLAB', year: 5 },
  { title: 'Node.js', year: 7 },
  { title: 'React Native', year: 8 },
  { title: 'Vue.js', year: 9 },
  { title: 'HTML/CSS', year: 10 },
  { title: 'Redux', year: 6 },
  { title: 'Spring Boot', year: 4 },
  { title: 'GraphQL', year: 5 },
  { title: 'Next.js', year: 3 },
  { title: 'REST APIs', year: 9 },
  { title: 'Docker', year: 12 },
  { title: 'Kubernetes', year: 7 },
  { title: 'Git', year: 11 },
  { title: 'Webpack', year: 8 },
  { title: 'Bootstrap', year: 6 },
  { title: 'Tailwind CSS', year: 3 },
  { title: 'Agile', year: 10 },
  { title: 'Scrum', year: 5 },
  { title: 'Python', year: 12 },
  { title: 'Flask', year: 7 },
  { title: 'Django', year: 6 },
  { title: 'TensorFlow', year: 4 },
  { title: 'PyTorch', year: 2 },
  { title: 'Pandas', year: 11 },
  { title: 'MySQL', year: 9 },
  { title: 'PostgreSQL', year: 10 },
  { title: 'AWS', year: 13 },
  { title: 'Azure', year: 9 },
  { title: 'Google Cloud', year: 8 },
  { title: 'Figma', year: 4 },
  { title: 'Adobe XD', year: 5 },
  { title: 'Machine Learning', year: 7 },
  { title: 'Deep Learning', year: 6 },
  { title: 'C++', year: 8 },
  { title: 'Java', year: 10 },
  { title: 'MATLAB', year: 5 },
  { title: 'Tableau', year: 9 },
  { title: 'Firebase', year: 6 },
  { title: 'Electron', year: 4 },
  { title: 'Flutter', year: 3 },
  { title: 'OAuth', year: 7 },
  { title: 'JSON', year: 10 },
  { title: 'XML', year: 9 },
  { title: 'WebRTC', year: 3 },
  { title: 'Three.js', year: 4 },
  { title: 'Chart.js', year: 5 },
  { title: 'C#', year: 7 },
  { title: 'Redux', year: 6 },
  { title: 'Nuxt.js', year: 5 },
  { title: 'Rust', year: 2 },
  { title: 'Golang', year: 7 },
  { title: 'Swift', year: 6 },
  { title: 'Terraform', year: 5 },
  { title: 'Ansible', year: 8 },
  { title: 'Jenkins', year: 10 },
  { title: 'CI/CD', year: 11 },
  { title: 'GitHub Actions', year: 4 },
  { title: 'JIRA', year: 8 },
  { title: 'Kanban', year: 7 },
  { title: 'SEO', year: 10 },
  { title: 'WebSockets', year: 9 },
  { title: 'Material-UI', year: 5 },
  { title: 'Highcharts', year: 3 },
  { title: 'WordPress', year: 11 },
  { title: 'Shopify', year: 9 },
  { title: 'Magento', year: 8 },
  { title: 'Excel', year: 12 },
  { title: 'Power BI', year: 7 },
  { title: 'Unreal Engine', year: 5 },
  { title: 'Unity', year: 6 },
  { title: 'SOAP', year: 10 },
  { title: 'Redis', year: 8 },
  { title: 'SQLite', year: 9 },
  { title: 'Bitbucket', year: 6 },
  { title: 'Prettier', year: 4 },
  { title: 'ESLint', year: 3 },
  { title: 'Ionic', year: 2 },
  { title: 'Svelte', year: 5 },
  { title: 'Angular', year: 8 },
  { title: 'PHP', year: 10 },
  { title: 'Adobe XD', year: 2 },
  { title: 'Computer Vision', year: 6 },
  { title: 'OpenCV', year: 7 },
  { title: 'NumPy', year: 8 },
  { title: 'Scikit-learn', year: 9 },
  { title: 'JSON', year: 10 },
];

export default skillList;
